### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rusuly** [rusuly/mysql_cdc#1]
- [x] BinlogClient
- [x] Row events
- [x] GTID
- [x] Write tests
- [x] Write docs
- [x] Replace **panic!**, **unwrap** and **expect** with Result
- [ ] Implement SSL
- [ ] Add buffering(like PipeReader from C#)
- [ ] Handle split packets
- [ ] Parse MySQL JSON
- [x] Handle heartbeat timeout and cancellation

**Comment by rusuly** [comment]
[mysqlcdc.json](https://github.com/rusuly/mysql_cdc/files/13538474/mysqlcdc.json)
Use this to determine what is left to migrate from C# MySqlCdc lib
